{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0bb47fce",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-08 17:02:34.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:34.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:34.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:34.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:34.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.110 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.110 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.111 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.201 Session state does not function when running a script without `streamlit run`\n",
      "2026-04-08 17:02:35.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 17:02:35.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from pymongo import MongoClient\n",
    "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "# --- CONFIGURACIÓN DE PÁGINA ---\n",
    "st.set_page_config(page_title=\"Predicciones Mundial 2026\", page_icon=\"⚽\", layout=\"wide\")\n",
    "\n",
    "# --- CARGA DE DATOS Y ENTRENAMIENTO (Todo en uno para que funcione) ---\n",
    "@st.cache_resource # Esto hace que solo cargue una vez y vaya rápido\n",
    "def cargar_y_entrenar():\n",
    "    client = MongoClient(\"mongodb://localhost:27017/\")\n",
    "    db = client[\"worldCup\"]\n",
    "    coll = db[\"matches\"]\n",
    "    datos = list(coll.find({}, {\"_id\": 0}))\n",
    "    \n",
    "    for d in datos:\n",
    "        win_val = str(d.get(\"winner\", \"Draw\"))\n",
    "        d[\"winner_clean\"] = win_val.split()[-1] if \" \" in win_val else win_val\n",
    "\n",
    "    df = pd.DataFrame(datos)\n",
    "    \n",
    "    le_team = LabelEncoder()\n",
    "    le_winner = LabelEncoder()\n",
    "    todos_los_equipos = pd.concat([df['home_team'], df['away_team']]).unique()\n",
    "    le_team.fit(todos_los_equipos)\n",
    "    \n",
    "    df['home_idx'] = le_team.transform(df['home_team'])\n",
    "    df['away_idx'] = le_team.transform(df['away_team'])\n",
    "    df['target'] = le_winner.fit_transform(df['winner_clean'])\n",
    "    \n",
    "    X = df[['home_idx', 'away_idx', 'elo_diff']].fillna(0)\n",
    "    \n",
    "    # Modelo de Ganador\n",
    "    model = RandomForestClassifier(n_estimators=100).fit(X, df['target'])\n",
    "    # Modelos de Goles\n",
    "    m_goles_h = RandomForestRegressor().fit(X, df['home_score'].fillna(0))\n",
    "    m_goles_a = RandomForestRegressor().fit(X, df['away_score'].fillna(0))\n",
    "    \n",
    "    return le_team, le_winner, model, m_goles_h, m_goles_a, df\n",
    "\n",
    "# Inicializamos\n",
    "le_team, le_winner, model, m_goles_h, m_goles_a, df = cargar_y_entrenar()\n",
    "\n",
    "# --- INTERFAZ DEL DASHBOARD ---\n",
    "st.title(\"🏆 FIFA World Cup 2026 Predictor\")\n",
    "st.markdown(\"---\")\n",
    "\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "with col1:\n",
    "    st.header(\"Configuración del Partido\")\n",
    "    local = st.selectbox(\"Selecciona Equipo Local\", sorted(le_team.classes_))\n",
    "    visitante = st.selectbox(\"Selecciona Equipo Visitante\", sorted(le_team.classes_))\n",
    "    elo_diff = st.slider(\"Ventaja de Elo (Fuerza)\", -500, 500, 0)\n",
    "\n",
    "with col2:\n",
    "    st.header(\"Resultado Predicho\")\n",
    "    if st.button(\"🔮 SIMULAR ENCUENTRO\"):\n",
    "        h_idx = le_team.transform([local])[0]\n",
    "        a_idx = le_team.transform([visitante])[0]\n",
    "        input_data = pd.DataFrame([[h_idx, a_idx, elo_diff]], \n",
    "                                 columns=['home_idx', 'away_idx', 'elo_diff'])\n",
    "        \n",
    "        # Predicciones\n",
    "        g_h = m_goles_h.predict(input_data)[0]\n",
    "        g_a = m_goles_a.predict(input_data)[0]\n",
    "        prob = model.predict_proba(input_data)[0]\n",
    "        ganador_idx = np.argmax(prob)\n",
    "        ganador_nombre = le_winner.classes_[ganador_idx]\n",
    "\n",
    "        # Mostrar marcador\n",
    "        st.markdown(f\"<h1 style='text-align: center;'>{local} {g_h:.0f} - {g_a:.0f} {visitante}</h1>\", unsafe_allow_html=True)\n",
    "        st.success(f\"El análisis indica que el resultado más probable es: **{ganador_nombre}**\")\n",
    "        \n",
    "        # Barra de probabilidades\n",
    "        st.write(\"Probabilidades:\")\n",
    "        st.progress(float(prob[ganador_idx]))\n",
    "\n",
    "st.markdown(\"---\")\n",
    "st.write(\"### 📈 Datos de entrenamiento\")\n",
    "st.write(f\"Modelo entrenado con **{len(df)}** partidos históricos.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
